use baseDatSop;
                                
insert into personal values	('asistenteN','asistenteN','1'),
								('asistente2','asistente2','1'),
                                ('asistente3','asistente3','1'),
								('gerenSop1','gerenSop1','2'),
                                ('gerenSop2','gerenSop2','2'),
                                ('gerenSop3','gerenSop3','2'),
								('gerenMan1','gerenMan1','3'),
                                ('gerenMan2','gerenMan2','3'),
                                ('gerenMan3','gerenMan3','3'),
								('ingeSop1','ingeSop1','4'),
                                ('ingeSop2','ingeSop2','4'),
                                ('ingeSop3','ingeSop3','4'),
								('ingMan1','ingMan1','5'),
                                ('ingMan2','ingMan2','5'),
                                ('ingMan3','ingMan3','5'),
								('editor1','editor1','6'), 
                                ('editor2','editor2','6'), 
                                ('editor3','editor3','6'),
                                ('comino','cominito','0'),
								('ola', 'olas','0'),
								('nimo', 'nimos','0'),
								('juanito09','juancho','0'),
                                ('pedro45', 'pedrito','0'),
                                ('pedro77', 'pedrito77','0'),
                                ('patrick77', 'patrikito','0'),
                                ('Williams', 'willicita','0');
                                
/*insert into reportes (descripcion, estatus, encargado, solucion) values	("El apartado de inicio de sesion lamentablemente no funciona en mi ordenador", "Abierto", "", ""),
																		("No puedo iniciar sesion, ya registre mi usuario y nada", "Abierto", "", ""),
                                                                        ("¿Cómo puedo registrar a una mascota en el apartado de Nueva Mascota?", "Abierto", "", ""),
                                                                        ("¿Cómo puedo realizar una cita con un veterinario?", "Abierto", "", ""),
                                                                        ("Tengo muchos problemas a la hora de agregar una mascota y nota", "Abierto", "", "");