use Kihon;
/* SOPORTE */                                
insert into usuarios values		('asistenteN','asistenteN','1'),
								('asistente2','asistente2','1'),
                                ('asistente3','asistente3','1'),
								('gerenSop1','gerenSop1','2'),
                                ('gerenSop2','gerenSop2','2'),
                                ('gerenSop3','gerenSop3','2'),
								('gerenMan1','gerenMan1','3'),
                                ('gerenMan2','gerenMan2','3'),
                                ('gerenMan3','gerenMan3','3'),
								('ingeSop1','ingeSop1','4'),
                                ('ingeSop2','ingeSop2','4'),
                                ('ingeSop3','ingeSop3','4'),
								('ingMan1','ingMan1','5'),
                                ('ingMan2','ingMan2','5'),
                                ('ingMan3','ingMan3','5'),
								('editor1','editor1','6'), 
                                ('editor2','editor2','6'), 
                                ('editor3','editor3','6'),
                                ('comino','cominito','0'),
								('ola', 'olas','0'),
								('nimo', 'nimos','0'),
								('juanito09','juancho','0'),
                                ('pedro45', 'pedrito','0'),
                                ('pedro77', 'pedrito77','0'),
                                ('patrick77', 'patrikito','0'),
                                ('Williams', 'willicita','0'),
                                ('pedrito', 'pedritoto','0');
/* PERSONALIDAD */
insert into personalidad values ("INTP"),
								("ENTP"),
                                ("ISTP"),
                                ("ESTP"),
                                ("INFP"),
                                ("ENFP"),
                                ("ISFP"),
                                ("ESFP"),
                                ("INFJ"),
                                ("ENFJ"),
                                ("ISFJ"),
                                ("ESFJ"),
                                ("ISTJ"),
                                ("ESTJ"),
                                ("INTJ"),
                                ("ENTJ");
/* CARRERAS */
/* Humanidades y Artes */
insert into carreras values	("Diseño Grafico", true, false, "HA"),
								("Administración de Archivos y Gestión Documental", true, false, "HA"), 
								("Arte y Diseño", true, false, "HA"),
								("Artes Visuales", true, false,  "HA"),
								("Bibliotecología y Estudios de la Información", true, false, "HA"),
								("Cinematografía ", true, false, "HA"),
								("Desarrollo y Gestión Interculturales", true, false,  "HA"),
								("Diseño y Comunicación Visual", true, false,  "HA"),
								("Enseñanza de Alemán como Lengua Extranjera", true, false, "HA"),
								("Enseñanza del Español como Lengua Extranjera", true, false, "HA"),
								("Enseñanza del Francés como Lengua Extranjera", true, false, "HA"),
								("Enseñanza del Italiano como Lengua Extranjera", true, false, "HA"),
								("Enseñanza de Inglés", true, false,  "HA"),
								("Estudios Latinoamericanos", true, false,  "HA"),
								("Etnomusicología", true, false,  "HA"),
								("Filosofía", true, false, "HA"),
								("Geohistoria", true, false, "HA"),
								("Historia", true, false, "HA"),
								("Historia del Arte", true, false,  "HA"),
								("Lengua y Literaturas Hispánicas", true, false, "HA"),
								("Lengua y Literaturas Modernas Alemanas", true, false, "HA"),
								("Lengua y Literaturas Modernas Francesas", true, false, "HA"),
								("Lengua y Literaturas Modernas Inglesas", true, false, "HA"),
								("Lengua y Literaturas Modernas Italianas", true, false, "HA"),
								("Lengua y Literaturas Modernas Portuguesas", true, false, "HA"),
								("Letras Clásicas", true, false, "HA"),
								("Lingüística Aplicada", true, false, "HA"),
								("Literatura Dramática y Teatro", true, false, "HA"),
								("Literatura Intercultural", true, false,  "HA"),
								("Canto", true, false, "HA"),
								("Composición", true, false, "HA"),
								("Educación Musical", true, false, "HA"),
								("Instrumentista", true, false, "HA"),
								("Piano", true, false, "HA"),
								("Música y Tecnología Artística", true, false, "HA"),
								("Pedagogía", true, false, "HA"),
								("Teatro y Actuación", true, false, "HA"),
								("Traducción", true, false, "HA");
                            
                            
/*ICFM*/
insert into carreras values	("Ingeniería Aeronáutica", false, true, "ICFM"),
								("Ingeniería Ambiental", false, true, "ICFM"),
								("Ingeniería Biomédica", false, true, "ICFM"),
								("Ingeniería Biónica", false, true, "ICFM"),
								("Ingeniería Bioquímica", false, true, "ICFM"),
								("Ingeniería Biotecnológica", false, true, "ICFM"),
								("Ingeniería Civil", false, true, "ICFM"),
								("Ingeniería Eléctrica", false, true, "ICFM"),
								("Ingeniería en Alimentos", false, true, "ICFM"),
								("Ingeniería en Computación", false, true, "ICFM"),
								("Ingeniería en Comunicaciones y Electrónica", false, true, "ICFM"),
								("Ingeniería en Control y Automatización", false, true, "ICFM"),
								("Ingeniería en Energía", false, true, "ICFM"),
								("Ingeniería en Informática", false, true, "ICFM"),
								("Ingeniería en Inteligencia Artificial", false, true, "ICFM"),
								("Ingeniería en Metalurgia y Materiales", false, true, "ICFM"),
								("Ingeniería en Movilidad Urbana", false, true, "ICFM"),
								("Ingeniería en Negocios Energéticos Sustentables", false, true, "ICFM"),
								("Ingeniería en Robótica Industrial", false, true, "ICFM"),
								("Ingeniería en Sistemas Ambientales", false, true, "ICFM"),
								("Ingeniería en Sistemas Automotrices", false, true, "ICFM"),
								("Ingeniería en Sistemas Computacionales", false, true, "ICFM"),
								("Ingeniería en Sistemas Energéticos y Redes Inteligentes", false, true, "ICFM"),
								("Ingeniería en Transporte", false, true, "ICFM"),
								("Ingeniería Farmacéutica", false, true, "ICFM"),
								("Ingeniería Ferroviaria", false, true, "ICFM"),
								("Ingeniería Fotónica", false, true, "ICFM"),
								("Ingeniería Geofísica", false, true, "ICFM"),
								("Ingeniería Geológica", false, true, "ICFM"),
								("Ingeniería Industrial", false, true, "ICFM"),
								("Ingeniería Matemática", false, true, "ICFM"),
								("Ingeniería Mecánica", false, true, "ICFM"),
								("Ingeniería Mecatrónica", false, true, "ICFM"),
								("Ingeniería Metalúrgica", false, true, "ICFM"),
								("Ingeniería Petrolera", false, true, "ICFM"),
								("Ingeniería Química Industrial", false, true, "ICFM"),
								("Ingeniería Química Petrolera", false, true, "ICFM"),
								("Ingeniería Telemática", false, true, "ICFM"),
								("Ingeniería Textil", false, true, "ICFM"),
								("Ingeniería Topográfica y Fotogramétrica", false, true, "ICFM"),
								("Ingeniero Arquitecto", false, true, "ICFM"),
								("Licenciatura en Ciencia de Datos", false, true, "ICFM"),
								("Licenciatura en Ciencias de la Informática", false, true, "ICFM"),
								("Licenciatura en Física y Matemáticas", false, true, "ICFM"),
								("Licenciatura en Matemática Algorítmica", false, true, "ICFM");
                                
/*CSA*/
insert into carreras values 	("Contador Público", false, true, "CSA"),
								("Licenciatura en Administración Industrial", false, true, "CSA"),
								("Licenciatura en Administración y Desarrollo Empresarial", false, true, "CSA"),
								("Licenciatura en Archivonomía", false, true, "CSA"),
								("Licenciatura en Biblioteconomía", false, true, "CSA"),
								("Licenciatura en Economía", false, true, "CSA"),
								("Licenciatura en Mercadotecnia Digital", false, true, "CSA"),
								("Licenciatura en Negocios Digitales", false, true, "CSA"),
								("Licenciatura en Negocios Internacionales", false, true, "CSA"),
								("Licenciatura en Relaciones Comerciales", false, true, "CSA"),
								("Licenciatura en Turismo", false, true, "CSA"),
								("Licenciatura en Turismo Sustentable", false, true, "CSA");
/*CMB*/
insert into carreras values 	("Licenciatura en Biología", false, true, "CMB"),
								("Licenciatura en Enfermería", false, true, "CMB"),
								("Licenciatura en Enfermería y Obstetricia", false, true, "CMB"),
								("Licenciatura en Nutrición", false, true, "CMB"),
								("Licenciatura en Odontología", false, true, "CMB"),
								("Licenciatura en Optometría", false, true, "CMB"),
								("Licenciatura en Psicología", false, true, "CMB"),
								("Licenciatura en Trabajo Social", false, true, "CMB"),
								("Médico Cirujano Homeópata", false, true, "CMB"),
								("Médico Cirujano Partero", false, true, "CMB"),
								("Químico Bacteriólogo y Parasitólogo", false, true, "CMB"),
								("Químico Farmacéutico Industrial", false, true, "CMB");
                                
/*PRUEBAS*/

insert into test_voc values(null, 57.5, 95.4, 66.2, 68.2, "pedrito");
insert into test_voc values(null, 100, 95.4, 66.2, 68.2, "pedrito");


select id_res, usuario, case greatest(ICFM, CSA, CMB, HA) when ICFM then "ICFM" when CSA then "CSA" when CMB then "CMB" when HA then "HA" end as area_max from test_voc where greatest(ICFM, CSA, CMB, HA) is not null and usuario = "pedrito" and id_res = (select MAX(id_res) from test_voc);
                                
/*insert into reportes (descripcion, estatus, encargado, solucion) values	("El apartado de inicio de sesion lamentablemente no funciona en mi ordenador", "Abierto", "", ""),
																		("No puedo iniciar sesion, ya registre mi usuario y nada", "Abierto", "", ""),
                                                                        ("¿Cómo puedo registrar a una mascota en el apartado de Nueva Mascota?", "Abierto", "", ""),
                                                                        ("¿Cómo puedo realizar una cita con un veterinario?", "Abierto", "", ""),
                                                                        ("Tengo muchos problemas a la hora de agregar una mascota y nota", "Abierto", "", "");