use Kihon;
/* SOPORTE */                                
insert into personal values	('asistenteN','asistenteN','1'),
								('asistente2','asistente2','1'),
                                ('asistente3','asistente3','1'),
								('gerenSop1','gerenSop1','2'),
                                ('gerenSop2','gerenSop2','2'),
                                ('gerenSop3','gerenSop3','2'),
								('gerenMan1','gerenMan1','3'),
                                ('gerenMan2','gerenMan2','3'),
                                ('gerenMan3','gerenMan3','3'),
								('ingeSop1','ingeSop1','4'),
                                ('ingeSop2','ingeSop2','4'),
                                ('ingeSop3','ingeSop3','4'),
								('ingMan1','ingMan1','5'),
                                ('ingMan2','ingMan2','5'),
                                ('ingMan3','ingMan3','5'),
								('editor1','editor1','6'), 
                                ('editor2','editor2','6'), 
                                ('editor3','editor3','6'),
                                ('comino','cominito','0'),
								('ola', 'olas','0'),
								('nimo', 'nimos','0'),
								('juanito09','juancho','0'),
                                ('pedro45', 'pedrito','0'),
                                ('pedro77', 'pedrito77','0'),
                                ('patrick77', 'patrikito','0'),
                                ('Williams', 'willicita','0'),
                                ('pedrito', 'pedritoto','0');
/* PERSONALIDAD */
insert into personalidad values ("INTP"),
								("ENTP"),
                                ("ISTP"),
                                ("ESTP"),
                                ("INFP"),
                                ("ENFP"),
                                ("ISFP"),
                                ("ESFP"),
                                ("INFJ"),
                                ("ENFJ"),
                                ("ISFJ"),
                                ("ESFJ"),
                                ("ISTJ"),
                                ("ESTJ"),
                                ("INTJ"),
                                ("ENTJ");
/* CARRERAS */
insert into carreras values	("Diseño Grafico", true, false, "HA"),
							("Administración de Archivos y Gestión Documental", true, false, "HA"), 
                            ("Arte y Diseño", true, false, "HA"),
                            ("Artes Visuales", true, false,  "HA"),
                            ("Bibliotecología y Estudios de la Información", true, false, "HA"),
                            ("Cinematografía ", true, false, "HA"),
                            ("Desarrollo y Gestión Interculturales", true, false,  "HA"),
                            ("Diseño y Comunicación Visual", true, false,  "HA"),
                            ("Enseñanza de Alemán como Lengua Extranjera", true, false, "HA"),
                            ("Enseñanza del Español como Lengua Extranjera", true, false, "HA"),
                            ("Enseñanza del Francés como Lengua Extranjera", true, false, "HA"),
                            ("Enseñanza del Italiano como Lengua Extranjera", true, false, "HA"),
                            ("Enseñanza de Inglés", true, false,  "HA"),
                            ("Estudios Latinoamericanos", true, false,  "HA"),
                            ("Etnomusicología", true, false,  "HA"),
                            ("Filosofía", true, false, "HA"),
                            ("Geohistoria", true, false, "HA"),
                            ("Historia", true, false, "HA"),
                            ("Historia del Arte", true, false,  "HA"),
                            ("Lengua y Literaturas Hispánicas", true, false, "HA"),
                            ("Lengua y Literaturas Modernas Alemanas", true, false, "HA"),
                            ("Lengua y Literaturas Modernas Francesas", true, false, "HA"),
                            ("Lengua y Literaturas Modernas Inglesas", true, false, "HA"),
                            ("Lengua y Literaturas Modernas Italianas", true, false, "HA"),
                            ("Lengua y Literaturas Modernas Portuguesas", true, false, "HA"),
                            ("Letras Clásicas", true, false, "HA"),
                            ("Lingüística Aplicada", true, false, "HA"),
                            ("Literatura Dramática y Teatro", true, false, "HA"),
                            ("Literatura Intercultural", true, false,  "HA"),
                            ("Canto", true, false, "HA"),
                            ("Composición", true, false, "HA"),
                            ("Educación Musical", true, false, "HA"),
                            ("Instrumentista", true, false, "HA"),
                            ("Piano", true, false, "HA"),
                            ("Música y Tecnología Artística", true, false, "HA"),
                            ("Pedagogía", true, false, "HA"),
                            ("Teatro y Actuación", true, false, "HA"),
                            ("Traducción", true, false, "HA");
                            
/*insert into reportes (descripcion, estatus, encargado, solucion) values	("El apartado de inicio de sesion lamentablemente no funciona en mi ordenador", "Abierto", "", ""),
																		("No puedo iniciar sesion, ya registre mi usuario y nada", "Abierto", "", ""),
                                                                        ("¿Cómo puedo registrar a una mascota en el apartado de Nueva Mascota?", "Abierto", "", ""),
                                                                        ("¿Cómo puedo realizar una cita con un veterinario?", "Abierto", "", ""),
                                                                        ("Tengo muchos problemas a la hora de agregar una mascota y nota", "Abierto", "", "");